version: '3'

services:
  localstack:
    image: 'localstack/localstack:0.13.0'
    restart: always
    environment:
      - AWS_DEFAULT_REGION=sa-east-1
      - SERVICES=s3
    ports:
      - 4566-4599:4566-4599
      - 8089:8080
    volumes:
      - ./docker/aws:/docker-entrypoint-initaws.d

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    deploy:
      resources:
        reservations:
          cpus: 0.5
          memory: 512M
        limits:
          cpus: 1
          memory: 1024M
    restart: on-failure
    depends_on:
      - localstack
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5